<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jhon Fernando Tascon Velasco">
<meta name="author" content="Lino Alexander Sinisterra">
<meta name="author" content="Juan Sebastián Chacon">
<meta name="dcterms.date" content="2025-09-15">

<title>Taller 3 - Modelo Regresión Multinomial</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Modelo_Multinomial_files/libs/clipboard/clipboard.min.js"></script>
<script src="Modelo_Multinomial_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Modelo_Multinomial_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Modelo_Multinomial_files/libs/quarto-html/popper.min.js"></script>
<script src="Modelo_Multinomial_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Modelo_Multinomial_files/libs/quarto-html/anchor.min.js"></script>
<link href="Modelo_Multinomial_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Modelo_Multinomial_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Modelo_Multinomial_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Modelo_Multinomial_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Modelo_Multinomial_files/libs/bootstrap/bootstrap-81267100e462c21b3d6c0d5bf76a3417.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="Modelo_Multinomial_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="Modelo_Multinomial_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Taller 3 - Modelo Regresión Multinomial</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Jhon Fernando Tascon Velasco </p>
             <p>Lino Alexander Sinisterra </p>
             <p>Juan Sebastián Chacon </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 15, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="información-general" class="level2">
<h2 class="anchored" data-anchor-id="información-general"><strong>0. Información general</strong></h2>
<p>En este trabajo se identificarán qué factores inciden en la preferencia de modo de transporte: Avión, Tren, Bus y Carro.</p>
<p>Este problema es idóneo para un modelo de regresión multinomial (MNL) porque:</p>
<ul>
<li><p>La variable de respuesta, Modo_Viaje, es nominal. No hay un orden natural entre las categorías (el Avión no es inherentemente mejor o peor que el Carro, o el Tren es mejor o peor que Bus, entre otros escenarios ).</p></li>
<li><p>Hay más de dos categorías, lo que descarta el uso de modelos de regresión logística binaria.</p></li>
<li><p>La categoría base para la interpretación del modelo, según la ordenación alfabética por defecto de R, será Avión. Todas las comparaciones se realizarán con respecto a esta categoría de referencia.</p></li>
<li><p>Además, Se presta especial atención a la estructura de los datos: para atributos específicos por alternativa (tiempo, costo) es imprescindible conservar el formato long (una fila por alternativa por individuo) y una variable binaria Choice que indique la alternativa escogida.</p></li>
</ul>
<p>Las variables a analizar son las siguientes:</p>
<div class="cell">
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<caption>Descripción de variables del estudio</caption>
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Variables</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Tipo_Variable</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Descripción</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Tiempo_Espera</td>
<td style="text-align: center;">Cuantitativa</td>
<td style="text-align: center;">Tiempo de espera en terminal</td>
</tr>
<tr class="even">
<td style="text-align: center;">Costo_Viaje</td>
<td style="text-align: center;">Cuantitativa</td>
<td style="text-align: center;">Costo del viaje</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Tiempo_Viaje</td>
<td style="text-align: center;">Cuantitativa</td>
<td style="text-align: center;">Tiempo de viaje</td>
</tr>
<tr class="even">
<td style="text-align: center;">Costo_Generalizado</td>
<td style="text-align: center;">Cuantitativa</td>
<td style="text-align: center;">Costo generalizado del viaje</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Ingresos_Hogar</td>
<td style="text-align: center;">Cuantitativa</td>
<td style="text-align: center;">Ingresos del hogar</td>
</tr>
<tr class="even">
<td style="text-align: center;">Tamano_Grupo</td>
<td style="text-align: center;">Ordinal</td>
<td style="text-align: center;">Tamaño del grupo que viaja</td>
</tr>
<tr class="odd">
<td style="text-align: center; font-weight: bold;">Modo_Viaje</td>
<td style="text-align: center; font-weight: bold;">Nominal/Variable objetivo</td>
<td style="text-align: center; font-weight: bold;">Modo de transporte</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="análisis-explora-torio" class="level2">
<h2 class="anchored" data-anchor-id="análisis-explora-torio"><strong>1. Análisis explora torio</strong></h2>
<section id="revisión-de-datos-faltantes" class="level3">
<h3 class="anchored" data-anchor-id="revisión-de-datos-faltantes"><strong>1.1. Revisión de datos faltantes</strong></h3>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small" data-quarto-postprocess="true">
<caption>Datos faltantes</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Modo_Viaje</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tiempo_Espera</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Costo_Viaje</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tiempo_Viaje</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Costo_Generalizado</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ingresos_Hogar</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tamano_Grupo</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>No se identificaron datos faltantes en el conjunto de datos, lo que permite un análisis completo sin necesidad de imputación.</p>
</section>
<section id="resumen-de-las-variables" class="level3">
<h3 class="anchored" data-anchor-id="resumen-de-las-variables"><strong>1.2. Resumen de las variables</strong></h3>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small" data-quarto-postprocess="true">
<caption>Descripción del conjunto de datos</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Modo_Viaje</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Tiempo_Espera</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Costo_Viaje</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Tiempo_Viaje</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Costo_Generalizado</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Ingresos_Hogar</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Tamano_Grupo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">Avión:58</td>
<td style="text-align: left;">Min. : 0.00</td>
<td style="text-align: left;">Min. : 2.0</td>
<td style="text-align: left;">Min. : 65.0</td>
<td style="text-align: left;">Min. : 30.0</td>
<td style="text-align: left;">Min. : 2.00</td>
<td style="text-align: left;">1:114</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">Bus :30</td>
<td style="text-align: left;">1st Qu.: 0.00</td>
<td style="text-align: left;">1st Qu.: 19.0</td>
<td style="text-align: left;">1st Qu.: 180.0</td>
<td style="text-align: left;">1st Qu.: 67.0</td>
<td style="text-align: left;">1st Qu.:20.00</td>
<td style="text-align: left;">2: 58</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">Carro:59</td>
<td style="text-align: left;">Median :20.00</td>
<td style="text-align: left;">Median : 33.0</td>
<td style="text-align: left;">Median : 305.0</td>
<td style="text-align: left;">Median :102.5</td>
<td style="text-align: left;">Median :34.50</td>
<td style="text-align: left;">3: 20</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">Tren :63</td>
<td style="text-align: left;">Mean :25.01</td>
<td style="text-align: left;">Mean : 47.4</td>
<td style="text-align: left;">Mean : 430.8</td>
<td style="text-align: left;">Mean :103.8</td>
<td style="text-align: left;">Mean :34.55</td>
<td style="text-align: left;">4: 15</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">3rd Qu.:40.00</td>
<td style="text-align: left;">3rd Qu.: 70.0</td>
<td style="text-align: left;">3rd Qu.: 720.0</td>
<td style="text-align: left;">3rd Qu.:132.8</td>
<td style="text-align: left;">3rd Qu.:50.00</td>
<td style="text-align: left;">5: 2</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Max. :99.00</td>
<td style="text-align: left;">Max. :180.0</td>
<td style="text-align: left;">Max. :1440.0</td>
<td style="text-align: left;">Max. :238.0</td>
<td style="text-align: left;">Max. :72.00</td>
<td style="text-align: left;">6: 1</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong><em>Conversión a factores:</em></strong> Las variables Tamano_Grupo y Modo_Viaje se convirtieron a factores. Se aclara que Tamano_Grupo es ordinal (los grupos tienen un orden de tamaño) y Modo_Viaje es nominal (sin orden).</p>
<p><strong><em>Hallazgos Clave:</em></strong> Existe una alta correlación entre Costo_Generalizado y (Costo_Viaje y Tiempo_Viaje), Costo_Generalizado es una variable compuesta de Costo_Viaje y Tiempo_Viaje, lo que genera una multicolinealidad que sesgaría el modelo. Por lo tanto, se eliminará esta variable.</p>
<section id="variables-numéricas" class="level4">
<h4 class="anchored" data-anchor-id="variables-numéricas"><strong>Variables numéricas</strong></h4>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Modelo_Multinomial_files/figure-html/numericas-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="960"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Modelo_Multinomial_files/figure-html/numericas-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p><strong><em>Los histogramas y boxplots permiten observar que:</em></strong></p>
<ul>
<li><p>Tiempo_Espera: La distribución de esta variable está sesgada a la derecha, con la mayoría de los valores concentrados en tiempos de espera bajos y algunos viajes con tiempos de espera significativamente más largos.</p></li>
<li><p>Costo_Viaje: De manera similar, se espera una distribución sesgada a la derecha, con muchos viajes de bajo costo y una cola de viajes más caros (probablemente los aéreos).</p></li>
<li><p>Tiempo_Viaje: La distribución de esta variable podría ser bimodal, con un pico para los viajes cortos (en carro o bus) y otro para los viajes largos (en avión).</p></li>
<li><p>Ingresos_Hogar: La distribución de los ingresos suele estar sesgada positivamente, con la mayoría de los hogares en rangos de ingresos medios y bajos, y una pequeña fracción de hogares con ingresos muy altos.</p></li>
</ul>
</section>
<section id="variables-cualitativas" class="level4">
<h4 class="anchored" data-anchor-id="variables-cualitativas"><strong>Variables cualitativas</strong></h4>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Modelo_Multinomial_files/figure-html/cualitativas-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong><em>Hallazgos del Análisis de Variables Cualitativas:</em></strong></p>
<ul>
<li><p>Dominio de Grupos Pequeños: La mayoría de las observaciones en el dataset corresponden a grupos de viaje pequeños. Se puede observar que los grupos de 1 o 2 personas son los más frecuentes en la muestra, representando la mayor proporción de los datos.</p></li>
<li><p>Frecuencia Decreciente: A medida que el tamaño del grupo aumenta, su frecuencia en el dataset disminuye significativamente. Los grupos de 5 o 6 personas son considerablemente menos comunes.</p></li>
<li><p>Relevancia para el Modelo: Este análisis exploratorio es crucial, ya que la variable Tamano_Grupo es un factor clave en el modelo de regresión multinomial. La distribución de esta variable indica que el modelo tendrá más información para estimar la probabilidad de elección de transporte para grupos pequeños que para grupos grandes.</p></li>
</ul>
</section>
</section>
<section id="análisis-bivariado" class="level3">
<h3 class="anchored" data-anchor-id="análisis-bivariado"><strong>1.3. Análisis bivariado</strong></h3>
<section id="variables-numéricas-vs.-modo-de-viaje" class="level4">
<h4 class="anchored" data-anchor-id="variables-numéricas-vs.-modo-de-viaje"><strong>Variables numéricas vs.&nbsp;Modo de viaje</strong></h4>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Modelo_Multinomial_files/figure-html/bivariado-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Hallazgos del Análisis Bivariado:</strong></p>
<ul>
<li><p>Relación Costo-Tiempo vs.&nbsp;Modo de Viaje: Los boxplots muestran que los viajeros que eligen avión tienen los costos más altos y los tiempos más cortos, mientras que los que eligen carro tienen los costos más bajos y los tiempos más largos. Esto es consistente con la idea de que los viajeros balancean el costo y la eficiencia.</p></li>
<li><p>Impacto de los Ingresos: Los ingresos del hogar son notablemente más altos para quienes eligen el avión, lo que sugiere que una mayor capacidad económica se asocia con una preferencia por opciones de viaje más rápidas.</p></li>
<li><p>Relación Tiempo de espera vs Modo de viaje: se evidencia que las personas que viajan en avión tienen mayores tiempos de espera vs los otros medios de transporte. Además, los carros no tienen tiempo de espeera. Esto úlitmo podría sesgar el modelo, por ende, no se utilizará esta variable.</p></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Modelo_Multinomial_files/figure-html/correlacion-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Hallazgos de la Matriz de Correlación:</strong></p>
<ul>
<li><p>Multicolinealidad Crítica: El hallazgo más importante es la correlación media-alta entre el Costo_Generalizado y el Tiempo_Viaje. Esta relación podría confirma una multicolinealidad. Por lo tanto, el Costo_Generalizado debe ser excluido del modelo de regresión para evitar estimaciones sesgadas y una interpretación incorrecta de los resultados.</p></li>
<li><p>Relaciones Intuitivas: Existe una correlación moderada entre Costo_Viaje y Tiempo_Espera (r=0.63). Esto tiene sentido, ya que los viajes más costosos (como los vuelos) suelen requerir más tiempo de espera en la terminal.</p></li>
<li><p>Ausencia de Correlaciones Fuertes: Fuera de la multicolinealidad detectada, no hay otras correlaciones fuertes entre las variables. Esto es positivo, ya que permite que el modelo estime los efectos individuales de cada variable de manera más limpia.</p></li>
</ul>
</section>
<section id="varables-cualitativas-vs.-modo-de-viaje" class="level4">
<h4 class="anchored" data-anchor-id="varables-cualitativas-vs.-modo-de-viaje"><strong>Varables cualitativas vs.&nbsp;Modo de viaje</strong></h4>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Modelo_Multinomial_files/figure-html/categoricas_porcentaje-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Hallazgos Clave de la Relación entre Tamaño del grupo y Modo de transporte:</strong></p>
<ul>
<li><p>El Carro domina para grupos grandes: El hallazgo más significativo es que, a medida que el tamaño del grupo aumenta, el carro se convierte en el modo de transporte abrumadoramente predominante. Esto se debe a la eficiencia logística y la reducción del costo por persona.</p></li>
<li><p>Avión y Tren para grupos pequeños: El avión y el tren son opciones más populares para grupos de una o dos personas. La frecuencia de estas opciones disminuye drásticamente a medida que el grupo se hace más grande, lo que sugiere que son menos atractivas o más costosas para viajes en grupo.</p></li>
<li><p>El Bus es una opción de nicho: El bus tiene una presencia relativamente baja en todos los tamaños de grupo, lo que lo posiciona como una opción menos preferida en comparación con las demás.</p></li>
</ul>
</section>
</section>
</section>
<section id="modelo-multinomial" class="level2">
<h2 class="anchored" data-anchor-id="modelo-multinomial"><strong>2. Modelo multinomial</strong></h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># weights:  40 (27 variable)
initial  value 291.121816 
iter  10 value 147.782539
iter  20 value 106.601389
iter  30 value 103.150919
iter  40 value 102.805410
iter  50 value 102.803334
final  value 102.803331 
converged</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Coefientes</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>      (Intercept) Costo_Viaje Tiempo_Viaje Ingresos_Hogar Tamano_Grupo.L
Bus      46.15633   -4.112399    0.5617427     -0.1735036      -88.24744
Carro    78.77012   -4.276600    0.5633502     -0.1358230      -30.83879
Tren     69.46713   -4.081489    0.5594685     -0.2012959      -60.33678
      Tamano_Grupo.Q Tamano_Grupo.C Tamano_Grupo^4 Tamano_Grupo^5
Bus         24.42756       59.00828      -4.453353      -99.21981
Carro       12.70779       36.21582      21.083529      -48.43903
Tren       -10.30403       25.61379      19.218698      -47.75568</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
P-values</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>      (Intercept) Costo_Viaje Tiempo_Viaje Ingresos_Hogar Tamano_Grupo.L
Bus             0           0            0              0              0
Carro           0           0            0              0              0
Tren            0           0            0              0              0
      Tamano_Grupo.Q Tamano_Grupo.C Tamano_Grupo^4 Tamano_Grupo^5
Bus                0              0              0              0
Carro              0              0              0              0
Tren               0              0              0              0</code></pre>
</div>
</div>
<section id="análisis-de-los-coeficientes-y-p-values" class="level3">
<h3 class="anchored" data-anchor-id="análisis-de-los-coeficientes-y-p-values"><strong>2.1. Análisis de los coeficientes y p-values</strong></h3>
<p>Se estima el modelo con las variables predictoras Costo_Viaje, Tiempo_Viaje, Ingresos_Hogar y Tamano_Grupo, y Avión como la categoría base. Con base en los p-values obtenidos, se observa que las variables incluidas en el modelo son estadísticamente significativas (p &lt; 0.05), lo cual indica que aportan información relevante para explicar la elección del modo de viaje.</p>
<ul>
<li><strong><em>Costo de viaje:</em></strong> Un aumento en una unidad del costo de viaje, se asocia con una disminución en las probabilidades logarítimicas de escoger bus versus avión en una cantidad de 4.11, carro versus avión de 4.28 y tren versus avión de 4.08.</li>
<li><strong><em>Tiempo de viaje:</em></strong> Un aumento en una unidad del tiempo de viaje, aumenta la probabilidad logarítimica de escoger bus versus avión en una cantidad de 0.56, carro versus avión de 0.56 y avión versus tren de 0.56.</li>
<li><strong><em>Ingresos del hogar:</em></strong> En cuanto a los ingresos del hogar, un aumento en una unidad de este factor se asocia con una disminución en las probabilidades logarítimicas de escoger bus versus avión en una cantidad de 0.17, carro versus avión de 0.14 y tren versus avión de 0.20.</li>
<li><strong><em>Tamaño del grupo:</em></strong> Por último, un aumento en una unidad del tamaño del grupo a viajar disminuye las probabilidades logarítimicas de escoger bus versus avión enm una cantidad de 88.25, carro versus avión en una cantidad de 30.84 y tren versus avión de 60.34.</li>
</ul>
</section>
<section id="odds-ratio" class="level3">
<h3 class="anchored" data-anchor-id="odds-ratio"><strong>2.2. Odds Ratio</strong></h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>       (Intercept) Costo_Viaje Tiempo_Viaje Ingresos_Hogar Tamano_Grupo.L
Bus   1.110297e+20  0.01636847     1.753726      0.8407142   4.727406e-39
Carro 1.619677e+34  0.01388981     1.756547      0.8729972   4.044674e-14
Tren  1.476355e+30  0.01688231     1.749742      0.8176705   6.252718e-27
      Tamano_Grupo.Q Tamano_Grupo.C Tamano_Grupo^4 Tamano_Grupo^5
Bus     4.062120e+10   4.236145e+25   1.163948e-02   8.116778e-44
Carro   3.303097e+05   5.349701e+15   1.433706e+09   9.187510e-22
Tren    3.349776e-05   1.330237e+11   2.221133e+08   1.819588e-21</code></pre>
</div>
</div>
<p><strong>Hallazgos del Modelo</strong></p>
<p>Los Odds Ratios nos permiten entender el impacto de cada variable en la elección del modo de viaje en comparación con el avión.</p>
<ul>
<li><p><strong><em>Costo de Viaje:</em></strong> en todos los casos, los odds son mneores a 1. Esto indica que por cada unidad adicional en el costo, las odds de elegir Tren, Bus y Carro sobre Avión disminuyen, lo que indica que a medida que el viaje se encarece, las personas son más propensas a elegir el Avión, que ya se considera la opción más cara. Específicamente, las probabilidades de elegir bus son un 98.4% menores que las de elegir avión, las probabilidades de elegir carro son un 98.6% menores y las probabilidades de elegir tren son un 98.3% menores.</p></li>
<li><p><strong><em>Tiempo del Viaje:</em></strong> Todos los valores son mayores que 1. Esto significa que por cada unidad que aumenta el tiempo de viaje, la probabilidad de elegir un modo de transporte terrestre sobre el avión aumenta. Las probabilidades para los tres modos de transporte son parecidas, y son aproximadamente 75% mayores que las de elegir avión.</p></li>
<li><p><strong><em>Ingresos del Hogar:</em></strong> Por cada mil dólares adicionales en los ingresos, las odds de elegir Bus sobre Avión disminuyen en un 16%. Esto sugiere que a mayor ingreso, las personas se inclinan más por el transporte aéreo, quizás valorando más el tiempo que el costo. Y de manera similar, por cada mil dólares adicionales en los ingresos, los odds de elegir los otros medios de transporte disminuyen sobre elegir avión: el del carro disminuyen un 13% y el de elergir tren disminuyen un 18%.</p></li>
<li><p><strong><em>Tamaño del Grupo:</em></strong> viajar en grupo hace que las opciones terrestres, especialmente el carro, sean mucho más atractivas en comparación con el avión.</p></li>
</ul>
</section>
<section id="análisis-marginal" class="level3">
<h3 class="anchored" data-anchor-id="análisis-marginal"><strong>2.3. Análisis marginal</strong></h3>
<div class="cell">
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<caption>Análisis marginal</caption>
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">group</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">contrast</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">p.value</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">s.value</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">conf.low</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">conf.high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Costo_Viaje</td>
<td style="text-align: center;">Avión</td>
<td style="text-align: center;">dY/dX</td>
<td style="text-align: center;">0.0000000</td>
<td style="text-align: center;">0.0000000</td>
<td style="text-align: center;">1.835362e+00</td>
<td style="text-align: center;">0.0664520</td>
<td style="text-align: center;">3.9115433</td>
<td style="text-align: center;">0.0000000</td>
<td style="text-align: center;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: center;">Costo_Viaje</td>
<td style="text-align: center;">Bus</td>
<td style="text-align: center;">dY/dX</td>
<td style="text-align: center;">0.0034838</td>
<td style="text-align: center;">0.0013013</td>
<td style="text-align: center;">2.677195e+00</td>
<td style="text-align: center;">0.0074242</td>
<td style="text-align: center;">7.0735579</td>
<td style="text-align: center;">0.0009333</td>
<td style="text-align: center;">0.0060342</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Costo_Viaje</td>
<td style="text-align: center;">Carro</td>
<td style="text-align: center;">dY/dX</td>
<td style="text-align: center;">-0.0144705</td>
<td style="text-align: center;">0.0016538</td>
<td style="text-align: center;">-8.749793e+00</td>
<td style="text-align: center;">0.0000000</td>
<td style="text-align: center;">58.6988235</td>
<td style="text-align: center;">-0.0177119</td>
<td style="text-align: center;">-0.0112291</td>
</tr>
<tr class="even">
<td style="text-align: center;">Costo_Viaje</td>
<td style="text-align: center;">Tren</td>
<td style="text-align: center;">dY/dX</td>
<td style="text-align: center;">0.0109867</td>
<td style="text-align: center;">0.0013141</td>
<td style="text-align: center;">8.360844e+00</td>
<td style="text-align: center;">0.0000000</td>
<td style="text-align: center;">53.8342189</td>
<td style="text-align: center;">0.0084112</td>
<td style="text-align: center;">0.0135623</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Ingresos_Hogar</td>
<td style="text-align: center;">Avión</td>
<td style="text-align: center;">dY/dX</td>
<td style="text-align: center;">0.0000000</td>
<td style="text-align: center;">0.0000000</td>
<td style="text-align: center;">1.887397e+00</td>
<td style="text-align: center;">0.0591069</td>
<td style="text-align: center;">4.0805292</td>
<td style="text-align: center;">0.0000000</td>
<td style="text-align: center;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: center;">Ingresos_Hogar</td>
<td style="text-align: center;">Bus</td>
<td style="text-align: center;">dY/dX</td>
<td style="text-align: center;">0.0005479</td>
<td style="text-align: center;">0.0012306</td>
<td style="text-align: center;">4.451836e-01</td>
<td style="text-align: center;">0.6561871</td>
<td style="text-align: center;">0.6078210</td>
<td style="text-align: center;">-0.0018641</td>
<td style="text-align: center;">0.0029598</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Ingresos_Hogar</td>
<td style="text-align: center;">Carro</td>
<td style="text-align: center;">dY/dX</td>
<td style="text-align: center;">0.0042728</td>
<td style="text-align: center;">0.0010796</td>
<td style="text-align: center;">3.957651e+00</td>
<td style="text-align: center;">0.0000757</td>
<td style="text-align: center;">13.6895314</td>
<td style="text-align: center;">0.0021568</td>
<td style="text-align: center;">0.0063888</td>
</tr>
<tr class="even">
<td style="text-align: center;">Ingresos_Hogar</td>
<td style="text-align: center;">Tren</td>
<td style="text-align: center;">dY/dX</td>
<td style="text-align: center;">-0.0048207</td>
<td style="text-align: center;">0.0012475</td>
<td style="text-align: center;">-3.864394e+00</td>
<td style="text-align: center;">0.0001114</td>
<td style="text-align: center;">13.1324141</td>
<td style="text-align: center;">-0.0072656</td>
<td style="text-align: center;">-0.0023757</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Tamano_Grupo</td>
<td style="text-align: center;">Avión</td>
<td style="text-align: center;">2 - 1</td>
<td style="text-align: center;">0.0000000</td>
<td style="text-align: center;">0.0000000</td>
<td style="text-align: center;">1.589138e+00</td>
<td style="text-align: center;">0.1120293</td>
<td style="text-align: center;">3.1580518</td>
<td style="text-align: center;">0.0000000</td>
<td style="text-align: center;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: center;">Tamano_Grupo</td>
<td style="text-align: center;">Avión</td>
<td style="text-align: center;">3 - 1</td>
<td style="text-align: center;">0.0000000</td>
<td style="text-align: center;">0.0000000</td>
<td style="text-align: center;">-1.519980e+00</td>
<td style="text-align: center;">0.1285161</td>
<td style="text-align: center;">2.9599793</td>
<td style="text-align: center;">0.0000000</td>
<td style="text-align: center;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Tamano_Grupo</td>
<td style="text-align: center;">Avión</td>
<td style="text-align: center;">4 - 1</td>
<td style="text-align: center;">0.0095238</td>
<td style="text-align: center;">0.0000000</td>
<td style="text-align: center;">4.050173e+06</td>
<td style="text-align: center;">0.0000000</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">0.0095238</td>
<td style="text-align: center;">0.0095238</td>
</tr>
<tr class="even">
<td style="text-align: center;">Tamano_Grupo</td>
<td style="text-align: center;">Avión</td>
<td style="text-align: center;">5 - 1</td>
<td style="text-align: center;">0.0095238</td>
<td style="text-align: center;">0.0000000</td>
<td style="text-align: center;">2.487501e+07</td>
<td style="text-align: center;">0.0000000</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">0.0095238</td>
<td style="text-align: center;">0.0095238</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Tamano_Grupo</td>
<td style="text-align: center;">Avión</td>
<td style="text-align: center;">6 - 1</td>
<td style="text-align: center;">0.0000001</td>
<td style="text-align: center;">0.0000001</td>
<td style="text-align: center;">8.948997e-01</td>
<td style="text-align: center;">0.3708407</td>
<td style="text-align: center;">1.4311285</td>
<td style="text-align: center;">-0.0000001</td>
<td style="text-align: center;">0.0000003</td>
</tr>
<tr class="even">
<td style="text-align: center;">Tamano_Grupo</td>
<td style="text-align: center;">Bus</td>
<td style="text-align: center;">2 - 1</td>
<td style="text-align: center;">-0.0947621</td>
<td style="text-align: center;">0.0480636</td>
<td style="text-align: center;">-1.971598e+00</td>
<td style="text-align: center;">0.0486555</td>
<td style="text-align: center;">4.3612521</td>
<td style="text-align: center;">-0.1889651</td>
<td style="text-align: center;">-0.0005592</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Tamano_Grupo</td>
<td style="text-align: center;">Bus</td>
<td style="text-align: center;">3 - 1</td>
<td style="text-align: center;">-0.0156164</td>
<td style="text-align: center;">0.0872240</td>
<td style="text-align: center;">-1.790381e-01</td>
<td style="text-align: center;">0.8579078</td>
<td style="text-align: center;">0.2211055</td>
<td style="text-align: center;">-0.1865724</td>
<td style="text-align: center;">0.1553396</td>
</tr>
<tr class="even">
<td style="text-align: center;">Tamano_Grupo</td>
<td style="text-align: center;">Bus</td>
<td style="text-align: center;">4 - 1</td>
<td style="text-align: center;">-0.1746788</td>
<td style="text-align: center;">0.0306286</td>
<td style="text-align: center;">-5.703136e+00</td>
<td style="text-align: center;">0.0000000</td>
<td style="text-align: center;">26.3412501</td>
<td style="text-align: center;">-0.2347097</td>
<td style="text-align: center;">-0.1146480</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Tamano_Grupo</td>
<td style="text-align: center;">Bus</td>
<td style="text-align: center;">5 - 1</td>
<td style="text-align: center;">-0.1746788</td>
<td style="text-align: center;">0.0306286</td>
<td style="text-align: center;">-5.703136e+00</td>
<td style="text-align: center;">0.0000000</td>
<td style="text-align: center;">26.3412502</td>
<td style="text-align: center;">-0.2347097</td>
<td style="text-align: center;">-0.1146480</td>
</tr>
<tr class="even">
<td style="text-align: center;">Tamano_Grupo</td>
<td style="text-align: center;">Bus</td>
<td style="text-align: center;">6 - 1</td>
<td style="text-align: center;">-0.1746788</td>
<td style="text-align: center;">0.0306286</td>
<td style="text-align: center;">-5.703136e+00</td>
<td style="text-align: center;">0.0000000</td>
<td style="text-align: center;">26.3412501</td>
<td style="text-align: center;">-0.2347097</td>
<td style="text-align: center;">-0.1146480</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Tamano_Grupo</td>
<td style="text-align: center;">Carro</td>
<td style="text-align: center;">2 - 1</td>
<td style="text-align: center;">0.0174830</td>
<td style="text-align: center;">0.0499041</td>
<td style="text-align: center;">3.503322e-01</td>
<td style="text-align: center;">0.7260894</td>
<td style="text-align: center;">0.4617810</td>
<td style="text-align: center;">-0.0803272</td>
<td style="text-align: center;">0.1152932</td>
</tr>
<tr class="even">
<td style="text-align: center;">Tamano_Grupo</td>
<td style="text-align: center;">Carro</td>
<td style="text-align: center;">3 - 1</td>
<td style="text-align: center;">-0.0377621</td>
<td style="text-align: center;">0.0805577</td>
<td style="text-align: center;">-4.687580e-01</td>
<td style="text-align: center;">0.6392426</td>
<td style="text-align: center;">0.6455646</td>
<td style="text-align: center;">-0.1956522</td>
<td style="text-align: center;">0.1201281</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Tamano_Grupo</td>
<td style="text-align: center;">Carro</td>
<td style="text-align: center;">4 - 1</td>
<td style="text-align: center;">-0.0022215</td>
<td style="text-align: center;">0.1142994</td>
<td style="text-align: center;">-1.943610e-02</td>
<td style="text-align: center;">0.9844932</td>
<td style="text-align: center;">0.0225468</td>
<td style="text-align: center;">-0.2262443</td>
<td style="text-align: center;">0.2218013</td>
</tr>
<tr class="even">
<td style="text-align: center;">Tamano_Grupo</td>
<td style="text-align: center;">Carro</td>
<td style="text-align: center;">5 - 1</td>
<td style="text-align: center;">0.4207496</td>
<td style="text-align: center;">0.0305122</td>
<td style="text-align: center;">1.378956e+01</td>
<td style="text-align: center;">0.0000000</td>
<td style="text-align: center;">141.2844166</td>
<td style="text-align: center;">0.3609468</td>
<td style="text-align: center;">0.4805524</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Tamano_Grupo</td>
<td style="text-align: center;">Carro</td>
<td style="text-align: center;">6 - 1</td>
<td style="text-align: center;">0.4466213</td>
<td style="text-align: center;">0.0255671</td>
<td style="text-align: center;">1.746863e+01</td>
<td style="text-align: center;">0.0000000</td>
<td style="text-align: center;">224.5784558</td>
<td style="text-align: center;">0.3965108</td>
<td style="text-align: center;">0.4967318</td>
</tr>
<tr class="even">
<td style="text-align: center;">Tamano_Grupo</td>
<td style="text-align: center;">Tren</td>
<td style="text-align: center;">2 - 1</td>
<td style="text-align: center;">0.0772791</td>
<td style="text-align: center;">0.0565179</td>
<td style="text-align: center;">1.367339e+00</td>
<td style="text-align: center;">0.1715190</td>
<td style="text-align: center;">2.5435601</td>
<td style="text-align: center;">-0.0334939</td>
<td style="text-align: center;">0.1880521</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Tamano_Grupo</td>
<td style="text-align: center;">Tren</td>
<td style="text-align: center;">3 - 1</td>
<td style="text-align: center;">0.0533785</td>
<td style="text-align: center;">0.0984097</td>
<td style="text-align: center;">5.424111e-01</td>
<td style="text-align: center;">0.5875354</td>
<td style="text-align: center;">0.7672524</td>
<td style="text-align: center;">-0.1395009</td>
<td style="text-align: center;">0.2462579</td>
</tr>
<tr class="even">
<td style="text-align: center;">Tamano_Grupo</td>
<td style="text-align: center;">Tren</td>
<td style="text-align: center;">4 - 1</td>
<td style="text-align: center;">0.1673765</td>
<td style="text-align: center;">0.1148847</td>
<td style="text-align: center;">1.456909e+00</td>
<td style="text-align: center;">0.1451415</td>
<td style="text-align: center;">2.7844679</td>
<td style="text-align: center;">-0.0577933</td>
<td style="text-align: center;">0.3925464</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Tamano_Grupo</td>
<td style="text-align: center;">Tren</td>
<td style="text-align: center;">5 - 1</td>
<td style="text-align: center;">-0.2555946</td>
<td style="text-align: center;">0.0324663</td>
<td style="text-align: center;">-7.872622e+00</td>
<td style="text-align: center;">0.0000000</td>
<td style="text-align: center;">48.0328013</td>
<td style="text-align: center;">-0.3192272</td>
<td style="text-align: center;">-0.1919619</td>
</tr>
<tr class="even">
<td style="text-align: center;">Tamano_Grupo</td>
<td style="text-align: center;">Tren</td>
<td style="text-align: center;">6 - 1</td>
<td style="text-align: center;">-0.2719425</td>
<td style="text-align: center;">0.0294215</td>
<td style="text-align: center;">-9.242992e+00</td>
<td style="text-align: center;">0.0000000</td>
<td style="text-align: center;">65.1773414</td>
<td style="text-align: center;">-0.3296076</td>
<td style="text-align: center;">-0.2142775</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Tiempo_Viaje</td>
<td style="text-align: center;">Avión</td>
<td style="text-align: center;">dY/dX</td>
<td style="text-align: center;">0.0000000</td>
<td style="text-align: center;">0.0000000</td>
<td style="text-align: center;">-1.844235e+00</td>
<td style="text-align: center;">0.0651489</td>
<td style="text-align: center;">3.9401152</td>
<td style="text-align: center;">0.0000000</td>
<td style="text-align: center;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: center;">Tiempo_Viaje</td>
<td style="text-align: center;">Bus</td>
<td style="text-align: center;">dY/dX</td>
<td style="text-align: center;">0.0000942</td>
<td style="text-align: center;">0.0000926</td>
<td style="text-align: center;">1.017842e+00</td>
<td style="text-align: center;">0.3087532</td>
<td style="text-align: center;">1.6954741</td>
<td style="text-align: center;">-0.0000872</td>
<td style="text-align: center;">0.0002757</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Tiempo_Viaje</td>
<td style="text-align: center;">Carro</td>
<td style="text-align: center;">dY/dX</td>
<td style="text-align: center;">0.0002324</td>
<td style="text-align: center;">0.0000856</td>
<td style="text-align: center;">2.713883e+00</td>
<td style="text-align: center;">0.0066500</td>
<td style="text-align: center;">7.2324364</td>
<td style="text-align: center;">0.0000645</td>
<td style="text-align: center;">0.0004002</td>
</tr>
<tr class="even">
<td style="text-align: center;">Tiempo_Viaje</td>
<td style="text-align: center;">Tren</td>
<td style="text-align: center;">dY/dX</td>
<td style="text-align: center;">-0.0003266</td>
<td style="text-align: center;">0.0000990</td>
<td style="text-align: center;">-3.298775e+00</td>
<td style="text-align: center;">0.0009711</td>
<td style="text-align: center;">10.0081259</td>
<td style="text-align: center;">-0.0005206</td>
<td style="text-align: center;">-0.0001325</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><strong>Hallazgos del Análisis Marginal:</strong></p>
<ol type="1">
<li><strong>Costo del viaje</strong>
<ul>
<li>Bus: El aumento en el costo incrementa ligeramente la probabilidad de elegir bus (+0.35 pp, p&lt;0.01).<br>
</li>
<li>Carro: Una mayor costo reduce significativamente la probabilidad de usar carro (–1.45 pp, p&lt;0.001).<br>
</li>
<li>Tren: El incremento del costo aumenta la probabilidad de usar tren (+1.1 pp, p&lt;0.001).<br>
<strong>Conclusión:</strong> El carro es el más sensible al costo, mientras bus y tren ganan peso relativo frente al avión.</li>
</ul></li>
<li><strong>Ingresos del hogar</strong>
<ul>
<li>Bus: Sin efecto significativo (p=0.65).<br>
</li>
<li>Carro: A mayor ingreso, aumenta la probabilidad de usar carro (+0.43 pp, p&lt;0.001).<br>
</li>
<li>Tren: Los ingresos más altos reducen la preferencia por tren (–0.48 pp, p&lt;0.001).<br>
<strong>Conclusión:</strong> Los hogares con más ingresos prefieren el carro frente al tren, mientras el bus permanece estable.</li>
</ul></li>
<li><strong>Tiempo de viaje</strong>
<ul>
<li>Bus: Efecto no significativo.<br>
</li>
<li>Carro: Incrementos en tiempo aumentan la probabilidad de elegir carro (+0.023 pp, p&lt;0.01).<br>
</li>
<li>Tren: Pierde atractivo con mayores tiempos de viaje (–0.033 pp, p&lt;0.001).<br>
<strong>Conclusión:</strong> El tren es más sensible al tiempo, mientras el carro tolera viajes largos.</li>
</ul></li>
<li><strong>Tamaño del grupo</strong>
<ul>
<li>Bus: Pierde atractivo desde grupos de 2 (–0.095 pp, p≈0.05) y más fuertemente con grupos de 4 a 6 (≈ –0.175 pp, p&lt;0.001).<br>
</li>
<li>Carro: Los grupos grandes prefieren fuertemente el carro (+0.42 a +0.45 pp, p&lt;0.001).<br>
</li>
<li>Tren: Grupos grandes abandonan el tren (–0.26 a –0.27 pp, p&lt;0.001).<br>
</li>
<li>Avión: Efectos marginales pequeños, con aumentos leves en grupos de 4 y 5 (+0.0095 pp).<br>
<strong>Conclusión:</strong> El carro es el gran ganador en grupos grandes, mientras que bus y tren pierden atractivo.</li>
</ul></li>
</ol>
<p><strong>Síntesis:</strong></p>
<ul>
<li>El costo del viaje afecta negativamente al carro, favoreciendo bus y tren.<br>
</li>
<li>El ingreso del hogar inclina las preferencias hacia el carro.<br>
</li>
<li>El tiempo de viaje penaliza al tren.<br>
</li>
<li>El tamaño del grupo refuerza fuertemente el uso del carro frente al bus y al tren.</li>
</ul>
</section>
<section id="análisis-de-las-predicciones" class="level3">
<h3 class="anchored" data-anchor-id="análisis-de-las-predicciones"><strong>2.4. Análisis de las predicciones</strong></h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Probabilidades medias por cada nivel de tamaño de grupo</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>pp.sim$Tamano_Grupo: 1
       Avión          Bus        Carro         Tren 
1.231788e-56 1.834502e-01 4.383172e-02 7.727181e-01 
------------------------------------------------------------ 
pp.sim$Tamano_Grupo: 2
       Avión          Bus        Carro         Tren 
5.021822e-49 7.040037e-02 4.285723e-02 8.867424e-01 
------------------------------------------------------------ 
pp.sim$Tamano_Grupo: 3
       Avión          Bus        Carro         Tren 
3.532199e-69 1.401616e-01 3.008804e-02 8.297503e-01 
------------------------------------------------------------ 
pp.sim$Tamano_Grupo: 4
       Avión          Bus        Carro         Tren 
4.451402e-30 3.236775e-41 3.127493e-02 9.687251e-01 
------------------------------------------------------------ 
pp.sim$Tamano_Grupo: 5
       Avión          Bus        Carro         Tren 
1.712114e-35 7.213883e-12 4.443178e-01 5.556822e-01 
------------------------------------------------------------ 
pp.sim$Tamano_Grupo: 6
       Avión          Bus        Carro         Tren 
7.264613e-49 1.982124e-17 1.000000e+00 3.172226e-10 </code></pre>
</div>
</div>
<p><strong>Hallazgos Clave de las Predicciones por Costo de Viaje:</strong></p>
<ul>
<li><p>Los gráficos de probabilidades predichas revelan que el costo del viaje es un factor determinante en la elección del modo de transporte, con efectos opuestos en las opciones de viaje.</p></li>
<li><p>Impacto Negativo en Opciones Terrestres: A medida que el costo del viaje aumenta, la probabilidad de elegir el Carro, el Bus o el Tren disminuye de forma constante. Este hallazgo confirma que los viajeros son sensibles al precio y tienden a evitar las opciones más económicas cuando estas se encarecen.</p></li>
<li><p>Impacto Positivo en el Transporte Aéreo: Por el contrario, la probabilidad de elegir el Avión aumenta a medida que el costo del viaje se incrementa. Esto se debe a que el avión es la alternativa más costosa del conjunto de datos. El modelo predice que cuando los costos de viaje son elevados (por ejemplo, debido a largas distancias), la probabilidad de que el viajero se decida por la opción aérea es mayor.</p></li>
<li><p>Segmentación por Sensibilidad al Costo: El modelo muestra que los usuarios de transporte terrestre son más sensibles al costo, mientras que quienes eligen el avión parecen menos afectados por aumentos en el precio, lo cual podría relacionarse con un perfil de mayor capacidad adquisitiva o con viajes en los que el tiempo cobra más relevancia que el dinero.</p></li>
<li><p>Relación Implícita con la Distancia: Dado que los mayores costos suelen asociarse con viajes más largos, es lógico que la opción aérea gane participación en esos escenarios, mientras que los modos terrestres resultan menos competitivos.</p></li>
<li><p>Evidencia de Sustitución entre Modos: La caída en la probabilidad de carro, bus y tren se compensa directamente con el aumento del avión, lo que refleja un patrón de sustitución: a medida que un viaje se vuelve más costoso, los viajeros no lo abandonan, sino que cambian de modo de transporte.</p></li>
<li><p>Polarización en la Elección: Se observa que el incremento en el costo del viaje polariza las decisiones: los viajeros se alejan progresivamente de las alternativas más económicas y se concentran en la opción aérea, reduciendo la diversidad en las elecciones disponibles.</p></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Gráficos de probabilidades</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Modelo_Multinomial_files/figure-html/analisis_probs2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Modelo_Multinomial_files/figure-html/analisis_probs2-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Modelo_Multinomial_files/figure-html/analisis_probs2-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Hallazgos Grafico probabilidades predichas Costo_Viaje</strong></p>
<ul>
<li><p>Relación Inversa para el Carro, Tren y Bus: La probabilidad de elegir el Carro, el Bus o el Tren muestra una clara relación inversa con el Costo_Viaje. A medida que el costo del viaje aumenta, la probabilidad de que un individuo elija cualquiera de estas tres opciones disminuye de forma constante. Este hallazgo es intuitivo: los viajeros son sensibles al precio y prefieren opciones más baratas.</p></li>
<li><p>Relación Directa para el Avión: En contraste, la probabilidad de elegir el Avión tiene una relación directa con el Costo_Viaje. A medida que el costo aumenta, la probabilidad de elegir el Avión también se incrementa. Este resultado, aunque pueda parecer contraintuitivo a primera vista, se explica por el hecho de que, en el contexto de este conjunto de datos, el Avión es la alternativa de viaje más costosa. El modelo reconoce que, si un viaje tiene un costo elevado (por ejemplo, debido a la distancia), es más probable que la elección sea el Avión que un viaje en Carro o Bus.</p></li>
<li><p>Impacto del Tamaño del Grupo: La faceta por Tamano_Grupo revela que la sensibilidad al costo varía según el número de viajeros. Se puede observar que para grupos más grandes, la probabilidad de elegir el Carro se mantiene relativamente alta incluso con un aumento en el costo, lo que sugiere que el costo por persona sigue siendo más atractivo. Por el contrario, los grupos pequeños son más propensos a cambiar de opción a medida que el costo aumenta.</p></li>
</ul>
</section>
<section id="diagnóstico" class="level3">
<h3 class="anchored" data-anchor-id="diagnóstico"><strong>2.5. Diagnóstico</strong></h3>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># weights:  8 (3 variable)
initial  value 291.121816 
final  value 283.758768 
converged</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Pseudo R²: 0.6377087 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Log-likelihood modelo nulo: -283.7588 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Log-likelihood modelo propuesto: -102.8033 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>AIC del modelo nulo: 573.5175 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>AIC del modelo propuesto: 259.6067 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>BIC del modelo nulo: 583.5589 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>BIC del modelo propuesto: 349.9786 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Matriz de confusión:</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Modelo_Multinomial_files/figure-html/diagnostico-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Reporte de clasificación:</code></pre>
</div>
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small" data-quarto-postprocess="true">
<caption>Estadísticas generales</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Accuracy</td>
<td style="text-align: right;">0.7904762</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kappa</td>
<td style="text-align: right;">0.7098081</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AccuracyLower</td>
<td style="text-align: right;">0.7291179</td>
</tr>
<tr class="even">
<td style="text-align: left;">AccuracyUpper</td>
<td style="text-align: right;">0.8434390</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AccuracyNull</td>
<td style="text-align: right;">0.3000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">AccuracyPValue</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">McnemarPValue</td>
<td style="text-align: right;">NaN</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small" data-quarto-postprocess="true">
<caption>Estadisticas por clase</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Class: Avión</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Class: Bus</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Class: Carro</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Class: Tren</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Sensitivity</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">0.2666667</td>
<td style="text-align: right;">0.8305085</td>
<td style="text-align: right;">0.8095238</td>
</tr>
<tr class="even">
<td style="text-align: left;">Specificity</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">0.9722222</td>
<td style="text-align: right;">0.9072848</td>
<td style="text-align: right;">0.8299320</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pos Pred Value</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">0.6153846</td>
<td style="text-align: right;">0.7777778</td>
<td style="text-align: right;">0.6710526</td>
</tr>
<tr class="even">
<td style="text-align: left;">Neg Pred Value</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">0.8883249</td>
<td style="text-align: right;">0.9319728</td>
<td style="text-align: right;">0.9104478</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Precision</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">0.6153846</td>
<td style="text-align: right;">0.7777778</td>
<td style="text-align: right;">0.6710526</td>
</tr>
<tr class="even">
<td style="text-align: left;">Recall</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">0.2666667</td>
<td style="text-align: right;">0.8305085</td>
<td style="text-align: right;">0.8095238</td>
</tr>
<tr class="odd">
<td style="text-align: left;">F1</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">0.3720930</td>
<td style="text-align: right;">0.8032787</td>
<td style="text-align: right;">0.7338129</td>
</tr>
<tr class="even">
<td style="text-align: left;">Prevalence</td>
<td style="text-align: right;">0.2761905</td>
<td style="text-align: right;">0.1428571</td>
<td style="text-align: right;">0.2809524</td>
<td style="text-align: right;">0.3000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Detection Rate</td>
<td style="text-align: right;">0.2761905</td>
<td style="text-align: right;">0.0380952</td>
<td style="text-align: right;">0.2333333</td>
<td style="text-align: right;">0.2428571</td>
</tr>
<tr class="even">
<td style="text-align: left;">Detection Prevalence</td>
<td style="text-align: right;">0.2761905</td>
<td style="text-align: right;">0.0619048</td>
<td style="text-align: right;">0.3000000</td>
<td style="text-align: right;">0.3619048</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Balanced Accuracy</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">0.6194444</td>
<td style="text-align: right;">0.8688966</td>
<td style="text-align: right;">0.8197279</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Hallazgos Clave:</strong></p>
<ul>
<li><p>El Pseudo R² de McFadden de 0.6378 indica un ajuste del modelo bueno. Por lo tanto, las variables que estamos analizando (costo de viaje, tiempo de viaje, ingresos y tamaño del grupo) explican aproximadamente el 63.8% de la variación en la elección de un modo de viaje.</p></li>
<li><p>En cuanto al log-likelihood, que también es una meida que indica qué tan bien se ajusta el modelo a los datos, se comparó con el modelo nulo (no hacer nada). Con base en las métricas, el modelo propuesto es mejor que que el modelo nulo, ya que su valor es menor (en valor abosluto), o más cercano a cero, por lo que el modelo propuesto tiene mejor ajuste.</p></li>
<li><p>Tanto el AIC como el BIC evalúan la calidad del modelo, balanceando el ajuste con la complejidad (número de variables). Para ambos criterios, el valor más bajo es el mejor. El modelo propuesto tiene valores de AIC y BIC que son significativamente más bajos que los del modelo nulo. Esto confirma que la complejidad añadida por las variables está más que justificada por la mejora en el ajuste del modelo.</p></li>
<li><p>Revisando la matriz de confusión, se puede decir que:</p>
<ul>
<li>El modelo es excelente para identificar viajes en avión.</li>
<li>En cuanto al bus, el modelono es muy bueno, ya que de los 13 datos para bus, el modelo fue capaz de clasificar correctamente 8.</li>
<li>El modelo presenta un rendimiento muy buen en decir si las personas escogen carro, ya que de 59 registros, el modelo acertó en 49 de ellos. Los fallos se dan principalmente con el Tren (7 casos) y en menor medida con Bus (3 casos).</li>
<li>Analizando los viajes en tren, el rendimiento del modelo también es bueno. De 63 casos, el modelo acertó en 51 de ellos. El modelo falla confundiéndo las mediciones principalmente con Carro (10 casos) y un poco con Bus (2 casos).</li>
</ul></li>
<li><p>Existe una notable confusión entre los tres medios de transporte terrestre. El modelo tiende a favorecer la predicción de “Tren” cuando tiene dudas entre bus, carro y tren.</p></li>
<li><p>En términos globales, la tasa de acierto del modelo es del 79.04%, lo que demuestra una buena capacidad predictiva y es significativa (p-value menor a 0.05). En cuánto al valor de Kappa (0.71), indica que el modelo es robusto.</p></li>
<li><p>Por clase, como se vio en la matriz de confusión, el modelo el capaz de predecir perfectamente la clase de avión. Para el carro, el rendimiento es bueno y equilibrado, teniendo un recall (proporción de casos verdaderos acertados) es del 83%, una precisión del 78% y un F1-Score del 80%. En cuánto al tren, el modelo es capaz de decir en un 81% los casos reales de tren, pero cuando el modelo dice que es “Tren”, sólo acierta el 67% de las veces, lo que se concluye que el modelo tiende a “sobre-predecir” esta clase. Por último, el rendimiento para predecir la clase “Bus” no es bueno, tiene un recall de 27%, una precisión del 62% y un F1-Score del 37%.</p></li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>