<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jhon Tascon Velasco">
<meta name="author" content="Lino Sinisterra">
<meta name="author" content="Juan Chacon">
<meta name="dcterms.date" content="2025-09-08">

<title>Taller 2 - Modelo Regresión Cuantílica</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Modelo_QR_files/libs/clipboard/clipboard.min.js"></script>
<script src="Modelo_QR_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Modelo_QR_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Modelo_QR_files/libs/quarto-html/popper.min.js"></script>
<script src="Modelo_QR_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Modelo_QR_files/libs/quarto-html/anchor.min.js"></script>
<link href="Modelo_QR_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Modelo_QR_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Modelo_QR_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Modelo_QR_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Modelo_QR_files/libs/bootstrap/bootstrap-81267100e462c21b3d6c0d5bf76a3417.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="Modelo_QR_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="Modelo_QR_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Taller 2 - Modelo Regresión Cuantílica</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Jhon Tascon Velasco </p>
             <p>Lino Sinisterra </p>
             <p>Juan Chacon </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 8, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="información-general" class="level2">
<h2 class="anchored" data-anchor-id="información-general"><strong>0. Información general</strong></h2>
<p>Este trabajo consiste identificar un caso real donde el interés esté en colas de la distribución (poblaciones muy vulnerables o muy favorecidas) y mostrar cómo la regresión cuantil (QR) revela patrones que el promedio (OLS) oculta.</p>
<p>En este caso, haremos el ejercicio con el dataset “Evaluación de la polución y calidad del aire” de kaggle: https://www.kaggle.com/datasets/mujtabamatin/air-quality-and-pollution-assessment. Este dataset se enfoca en envaluaciones de la calidad de aire en varias regiones del mundo. El dataset contiene 5000 muestras capturando factores ambientales y demográficos que influyen en los niveles de polución.</p>
<p>La pregunta de investigación es: ¿Cómo influyen los facotres meteorológicos, de densidad de población y cercanía a zonas industriales los diferentes niveles de CO?</p>
</section>
<section id="análisis-exploratorio" class="level2">
<h2 class="anchored" data-anchor-id="análisis-exploratorio"><strong>1. Análisis exploratorio</strong></h2>
<p>Las variables a analizar son las siguientes:</p>
<div class="cell">
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<caption>Descripción de variables del estudio</caption>
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Variables</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Unidades</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Descripción</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Temperatura</td>
<td style="text-align: center;">°C</td>
<td style="text-align: center;">Temperatura media de la región</td>
</tr>
<tr class="even">
<td style="text-align: center;">Humedad</td>
<td style="text-align: center;">%</td>
<td style="text-align: center;">Humedad relativa registrada en la región</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Concentración PM2.5</td>
<td style="text-align: center;">µg/m³</td>
<td style="text-align: center;">Niveles de partículas finas</td>
</tr>
<tr class="even">
<td style="text-align: center;">Concentración PM10</td>
<td style="text-align: center;">µg/m³</td>
<td style="text-align: center;">Niveles de partículas gruesas (no se trabajará en el estudio)</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Concentración NO2</td>
<td style="text-align: center;">ppb</td>
<td style="text-align: center;">Niveles de dióxido de nitrógeno (no se trabajará en el estudio)</td>
</tr>
<tr class="even">
<td style="text-align: center;">Concentración SO2</td>
<td style="text-align: center;">ppb</td>
<td style="text-align: center;">Niveles de dióxido de azufre (no se trabajará en el estudio)</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Cercanía a Áreas Industriales</td>
<td style="text-align: center;">km</td>
<td style="text-align: center;">Distancia a la zona industrial más cercana</td>
</tr>
<tr class="even">
<td style="text-align: center;">Densidad de población</td>
<td style="text-align: center;">personas/km²</td>
<td style="text-align: center;">Número de personas por kilómetro cuadrado en la región</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Calidad del aire</td>
<td style="text-align: center;">Categorías</td>
<td style="text-align: center;">Clasificación: Bueno, Moderado, Pobre, Peligroso</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold;">Concentración de CO</td>
<td style="text-align: center; font-weight: bold;">ppb</td>
<td style="text-align: center; font-weight: bold;">Variable objetivo: Niveles de monóxido de carbono</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Los percentiles a trabajar serán: 0.05, 0.25, 0.50, 0.75 y 0.95</p>
<p>A continuación, se hace un análisis exploratorio de los datos:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Visualización de los 10 primeros registros del conjunto de datos:</code></pre>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 13%">
<col style="width: 8%">
<col style="width: 6%">
<col style="width: 5%">
<col style="width: 30%">
<col style="width: 20%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Temperatura</th>
<th style="text-align: right;">Humedad</th>
<th style="text-align: right;">PM2.5</th>
<th style="text-align: right;">CO</th>
<th style="text-align: right;">Cercania_Areas_Industriales</th>
<th style="text-align: right;">Densidad_Poblacion</th>
<th style="text-align: left;">Calidad_Aire</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">29.8</td>
<td style="text-align: right;">59.1</td>
<td style="text-align: right;">5.2</td>
<td style="text-align: right;">1.72</td>
<td style="text-align: right;">6.3</td>
<td style="text-align: right;">319</td>
<td style="text-align: left;">Moderate</td>
</tr>
<tr class="even">
<td style="text-align: right;">28.3</td>
<td style="text-align: right;">75.6</td>
<td style="text-align: right;">2.3</td>
<td style="text-align: right;">1.64</td>
<td style="text-align: right;">6.0</td>
<td style="text-align: right;">611</td>
<td style="text-align: left;">Moderate</td>
</tr>
<tr class="odd">
<td style="text-align: right;">23.1</td>
<td style="text-align: right;">74.7</td>
<td style="text-align: right;">26.7</td>
<td style="text-align: right;">1.63</td>
<td style="text-align: right;">5.2</td>
<td style="text-align: right;">619</td>
<td style="text-align: left;">Moderate</td>
</tr>
<tr class="even">
<td style="text-align: right;">27.1</td>
<td style="text-align: right;">39.1</td>
<td style="text-align: right;">6.1</td>
<td style="text-align: right;">1.15</td>
<td style="text-align: right;">11.1</td>
<td style="text-align: right;">551</td>
<td style="text-align: left;">Good</td>
</tr>
<tr class="odd">
<td style="text-align: right;">26.5</td>
<td style="text-align: right;">70.7</td>
<td style="text-align: right;">6.9</td>
<td style="text-align: right;">1.01</td>
<td style="text-align: right;">12.7</td>
<td style="text-align: right;">303</td>
<td style="text-align: left;">Good</td>
</tr>
<tr class="even">
<td style="text-align: right;">39.4</td>
<td style="text-align: right;">96.6</td>
<td style="text-align: right;">14.6</td>
<td style="text-align: right;">1.82</td>
<td style="text-align: right;">3.1</td>
<td style="text-align: right;">674</td>
<td style="text-align: left;">Hazardous</td>
</tr>
<tr class="odd">
<td style="text-align: right;">41.7</td>
<td style="text-align: right;">82.5</td>
<td style="text-align: right;">1.7</td>
<td style="text-align: right;">1.80</td>
<td style="text-align: right;">4.6</td>
<td style="text-align: right;">735</td>
<td style="text-align: left;">Poor</td>
</tr>
<tr class="even">
<td style="text-align: right;">31.0</td>
<td style="text-align: right;">59.6</td>
<td style="text-align: right;">5.0</td>
<td style="text-align: right;">1.38</td>
<td style="text-align: right;">6.3</td>
<td style="text-align: right;">443</td>
<td style="text-align: left;">Moderate</td>
</tr>
<tr class="odd">
<td style="text-align: right;">29.4</td>
<td style="text-align: right;">93.8</td>
<td style="text-align: right;">10.3</td>
<td style="text-align: right;">2.03</td>
<td style="text-align: right;">5.4</td>
<td style="text-align: right;">486</td>
<td style="text-align: left;">Poor</td>
</tr>
<tr class="even">
<td style="text-align: right;">33.2</td>
<td style="text-align: right;">80.5</td>
<td style="text-align: right;">11.1</td>
<td style="text-align: right;">1.69</td>
<td style="text-align: right;">4.9</td>
<td style="text-align: right;">535</td>
<td style="text-align: left;">Poor</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="análisis-univariado" class="level3">
<h3 class="anchored" data-anchor-id="análisis-univariado"><strong>1.1. Análisis univariado</strong></h3>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 2%">
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 10%">
<col style="width: 22%">
<col style="width: 15%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Temperatura</th>
<th style="text-align: left;">Humedad</th>
<th style="text-align: left;">PM2.5</th>
<th style="text-align: left;">CO</th>
<th style="text-align: left;">Cercania_Areas_Industriales</th>
<th style="text-align: left;">Densidad_Poblacion</th>
<th style="text-align: left;">Calidad_Aire</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">Min. :13.40</td>
<td style="text-align: left;">Min. : 36.00</td>
<td style="text-align: left;">Min. : 0.00</td>
<td style="text-align: left;">Min. :0.65</td>
<td style="text-align: left;">Min. : 2.500</td>
<td style="text-align: left;">Min. :188.0</td>
<td style="text-align: left;">Good :2000</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">1st Qu.:25.10</td>
<td style="text-align: left;">1st Qu.: 58.30</td>
<td style="text-align: left;">1st Qu.: 4.60</td>
<td style="text-align: left;">1st Qu.:1.03</td>
<td style="text-align: left;">1st Qu.: 5.400</td>
<td style="text-align: left;">1st Qu.:381.0</td>
<td style="text-align: left;">Moderate :1500</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">Median :29.00</td>
<td style="text-align: left;">Median : 69.80</td>
<td style="text-align: left;">Median : 12.00</td>
<td style="text-align: left;">Median :1.41</td>
<td style="text-align: left;">Median : 7.900</td>
<td style="text-align: left;">Median :494.0</td>
<td style="text-align: left;">Poor :1000</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">Mean :30.03</td>
<td style="text-align: left;">Mean : 70.06</td>
<td style="text-align: left;">Mean : 20.14</td>
<td style="text-align: left;">Mean :1.50</td>
<td style="text-align: left;">Mean : 8.425</td>
<td style="text-align: left;">Mean :497.4</td>
<td style="text-align: left;">Hazardous: 500</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">3rd Qu.:34.00</td>
<td style="text-align: left;">3rd Qu.: 80.30</td>
<td style="text-align: left;">3rd Qu.: 26.10</td>
<td style="text-align: left;">3rd Qu.:1.84</td>
<td style="text-align: left;">3rd Qu.:11.100</td>
<td style="text-align: left;">3rd Qu.:600.0</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">Max. :58.60</td>
<td style="text-align: left;">Max. :128.10</td>
<td style="text-align: left;">Max. :295.00</td>
<td style="text-align: left;">Max. :3.72</td>
<td style="text-align: left;">Max. :25.800</td>
<td style="text-align: left;">Max. :957.0</td>
<td style="text-align: left;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>El resumen estadístico nos ofrece una primera vista de las variables. La Concentración de CO, que es nuestra variable objetivo de este estudio, varía desde 0.65 ppb hasta 3.72 ppb, con una media de 1.50 ppb y una mediana de 7.9 ppb. La cercanía entre la media y la mediana sugiere una distribución relativamente simétrica. Otras variables como PM2.5 y Densidad de Población muestran una diferencia más marcada entre la media y la mediana, lo que indica una posible asimetría en sus distribuciones.</p>
<section id="distribución-de-las-variables-numéricas" class="level4">
<h4 class="anchored" data-anchor-id="distribución-de-las-variables-numéricas"><strong>1.1.1. Distribución de las variables numéricas</strong></h4>
<p>Puntos Clave:</p>
<ul>
<li><strong>Cercania_Areas_industriales</strong>: Esta variable presenta una distribución bimodal (con dos picos claros), lo que sugiere que los datos, uno de localidades muy cercanas a zonas industriales (el primer pico) y otro grupo un poco más alejado (el segundo pico, más alto). También tiene un sesgo a la derecha, indicando que hay algunas localidades excepcionalmente cercanas.</li>
<li><strong>CO</strong>: La distribución de la (CO) es marcadamente asimétrica, con un fuerte sesgo positivo carbono(a la derecha). Esto indica que la gran mayoría de las mediciones registran niveles de CO muy bajos, agrupándose cerca del valor mínimo. Además, presenta un segundo pico no muy marcado, pero podemos ver que presenta una distribución bimodal.</li>
<li><strong>PM2.5</strong>: De manera muy similar al CO, la concentración de (PM2.5) presenta una distribución con un sesgo positivo excesivo. La considerable mayoría de los datos se concentra en valores muy bajos, prácticamente cercanos a cero, lo que representa condiciones de aire generalmente limpio. No obstante, la distribución se caracteriza por una cola extendida y una gran cantidad de valores atípicos en el extremo superior, evidenciando zonas de muy mala calidad del aire con picos de contaminación severa.</li>
<li><strong>Temperatura y Densidad de Población</strong>: Presentan rangos amplios y distribuciones simétricas, cubriendo diversas condiciones climáticas. La mayoría de los valores se concentran alrededor de la media, con una disminución gradual hacia los extremos.</li>
<li><strong>Humedad</strong>: Muestra una clara asimetría positiva, pero con un ligero sesgo a la izquierda (asimetría negativa). Esto indica que son más frecuentes los valores de humedad altos (por encima del 50%) que los muy bajos.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Modelo_QR_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Modelo_QR_files/figure-html/unnamed-chunk-4-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="distribución-de-las-variables-categóricas" class="level4">
<h4 class="anchored" data-anchor-id="distribución-de-las-variables-categóricas"><strong>1.1.2. Distribución de las variables categóricas</strong></h4>
<p>Puntos Clave:</p>
<ul>
<li><strong>Calidad_Aire</strong>: La variable Calidad del Aire presenta una distribución heterogénea pero relativamente balanceada entre sus cuatro categorías. La mayor proporción corresponde a la categoría Good (40%), seguida por Moderate (30%), lo que indica que en la mayoría de las observaciones la calidad del aire se encuentra en niveles aceptables o moderados. Sin embargo, también se evidencia que un 20% de los registros corresponden a condiciones Poor y un 10% a situaciones Hazardous, reflejando episodios de contaminación con riesgos significativos para la salud. Esta distribución es adecuada para el análisis, ya que garantiza variabilidad suficiente en los datos sin presentar un desbalance extremo entre clases, aunque la menor representación de la categoría Hazardous requiere especial atención para evitar que sea subestimada en los modelos predictivos.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Modelo_QR_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="análisis-bivariado" class="level4">
<h4 class="anchored" data-anchor-id="análisis-bivariado"><strong>1.2. Análisis bivariado</strong></h4>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Modelo_QR_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="variables-numéricas-vs-co" class="level5">
<h5 class="anchored" data-anchor-id="variables-numéricas-vs-co"><strong>Variables numéricas vs CO</strong></h5>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Modelo_QR_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El CO con las demás variables numéricas presentan relaciones medias-altas, especialmente con la temperatura (relación positiva), húmedad (positiva), densidad de población (positiva) y cercanía a áreas industriales (negativa).</p>
<ul>
<li><strong>Temperatura</strong>: En cuanto a la relación con la temperatura, se puede ver que a mayor temperatura, las concentraciones de CO tienden a ser mayores.</li>
<li><strong>Húmedad</strong>: muy similar a la temperatura en cuanto a su relación. Sin embgargo, en zonas medias de húmedad (60%-90%) hay una mayor variabilidad de concentración de CO.</li>
<li><strong>Densidad de población</strong>: comportamiento similar a los anteriores. Sin embargo, en zonas de baja concentración de población (alrededor de 200 a 300 personas/km), la concentración de CO tiende a ser constante, moviéndose entre 0.5 y 1.5 ppb.</li>
<li><strong>Cercanía a áreas industriales</strong>: en este caso, la relación es inversa: entre más cercano esté una región a zonas industriales, la concentración de CO tiende a ser mayor. La relación no es del todo lineal.</li>
</ul>
</section>
<section id="variables-categóricas-vs-co" class="level5">
<h5 class="anchored" data-anchor-id="variables-categóricas-vs-co"><strong>Variables categóricas vs CO</strong></h5>
<div class="cell" data-layout-align="center" data-fig.weight="1">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Modelo_QR_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>En cuanto a la calidad del aire, se ve que el CO influye en gran medida: en zonas donde la calidad del aire es buena o moderada, los niveles de CO son menores, mientras en regiones con calidad de aire pobre o peligroso, el nivel de CO es mayor.</p>
</section>
</section>
</section>
</section>
<section id="modelo-de-regresión-cuantílica" class="level2">
<h2 class="anchored" data-anchor-id="modelo-de-regresión-cuantílica"><strong>2. Modelo de regresión cuantílica</strong></h2>
<section id="modelo-completo" class="level3">
<h3 class="anchored" data-anchor-id="modelo-completo">Modelo completo</h3>
<p><span class="math display">\[
Q_\tau(CO|X) = \beta_0(\tau) + \beta_1(\tau)Temperatura + \beta_2(\tau)Humedad + \beta_3(\tau)Cercania Areas Industriales +
\]</span></p>
<p><span class="math display">\[
\beta_4(\tau)log(Cercania Areas Industriales) + \beta_5(\tau)Densidad_Poblacion + \beta_6(\tau)Calidad Aire
\]</span></p>
</section>
<section id="modelo-ols" class="level3">
<h3 class="anchored" data-anchor-id="modelo-ols"><strong>2.1. Modelo OLS</strong></h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = form, data = df)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.42083 -0.11555 -0.00125  0.11103  1.19823 

Coefficients:
                                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                          8.967e-01  4.954e-02  18.101  &lt; 2e-16 ***
Temperatura                         -4.611e-04  7.148e-04  -0.645  0.51892    
Humedad                             -2.316e-04  2.552e-04  -0.907  0.36420    
PM2.5                                3.579e-04  1.416e-04   2.527  0.01154 *  
Cercania_Areas_Industriales         -1.162e-02  4.248e-03  -2.736  0.00624 ** 
I(log(Cercania_Areas_Industriales))  1.025e-01  3.438e-02   2.981  0.00289 ** 
Densidad_Poblacion                   2.691e-05  2.706e-05   0.994  0.32009    
Calidad_AireModerate                 5.033e-01  1.227e-02  41.031  &lt; 2e-16 ***
Calidad_AirePoor                     1.006e+00  1.737e-02  57.911  &lt; 2e-16 ***
Calidad_AireHazardous                1.506e+00  2.371e-02  63.509  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2231 on 4990 degrees of freedom
Multiple R-squared:  0.8333,    Adjusted R-squared:  0.833 
F-statistic:  2773 on 9 and 4990 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><strong>1. Temperatura: -0.00046</strong> Diferencia no significativa (p = 0.519; IC95% cruza 0). Con estos datos, no hay evidencia de efecto promedio de la temperatura sobre el CO.</p>
<p><strong>2. Humedad: -0.00023</strong> Diferencia no significativa (p = 0.346; IC95% cruza 0). Con estos datos, no hay evidencia de efecto promedio de la humedad sobre el CO.</p>
<p><strong>3. Partículas finas (PM2.5): 0.00036</strong> Cada nivel adicional de partículas finas en el aire, se asocia con +0.00035 unidades de CO (p.&nbsp;&lt; 0.05; IC95% ≈ [0.0008, 0.00064]), manteniendo lo demás constante.</p>
<p><strong>4. Cercanía a áreas industriales: -0.0162 y log(Cercania_Areas_Industriales): 0.1025</strong> La cercanía a zonas industriales aumenta los niveles de CO en las regiones, es decir, entre más cerca a áreas industriales, mayores son los niveles de CO. Sin embargo, entre más lejos de zonas industriales, los niveles de CO bajan pero no constantemente. El efecto marginal es el siguiente:</p>
<p><span class="math display">\[
\frac{\partial CO}{\partial Cercania Areas Industriales} = -0.0162 + \frac{0.1025}{Cercania Areas Industriales}
\]</span></p>
<p>Si está muy cerca a áreas industriales, al disminuir 1 km aumenta 0.0863 los niveles de CO, alejarse 5 km aumenta los niveles de CO en 0.0043. Y si se encuentra a 10 km de las áreas industriales, un aumento en 1 km de las áreas industriales, los niveles de CO disminuyen en -0.006 bbp.</p>
<p>Ambos son significativos (p.&nbsp;&lt; 0.01).</p>
<p><strong>5. Densidad de población: 0.000027</strong> Diferencia no significativa (p = 0.32; IC95% cruza 0). Con estos datos, no hay evidencia de efecto promedio de la densidad de población sobre el CO.</p>
<p><strong>6. Calidad del aire</strong> A mismo nivel de partículas finas y cercanía a áreas industriales:</p>
<ul>
<li>Si la calidad del aire es moderada, el nivel de CO aumenta en 0.503 unidades vs si la calidad de aire es bueno (p.&nbsp;&lt; 0.001; IC95% ≈ [0.478, 0.528]).</li>
<li>Si la calidad del aire es pobre, el nivel de CO aumenta en 1.006 unidades vs si la calidad de aire es bueno (p.&nbsp;&lt; 0.001; IC95% ≈ [0.972, 1.04]).</li>
<li>Si la calidad del aire es peligrosa, el nivel de CO aumenta en 1.506 unidades vs si la calidad de aire es bueno (p.&nbsp;&lt; 0.001; IC95% ≈ [1.459, 1.553]).</li>
</ul>
<p><strong>7. Medidas globales del Modelo</strong> A nivel global, el modelo tiene los siguientes valores:</p>
<ul>
<li>Residual standard error (0.2231): en promedio, el modelo se equivoca ±0.22 unidades al predecir.</li>
<li>R² = 0.8333: el modelo explica aproximadamente el 83% de la variabilidad de la variable dependiente → muy buen ajuste.</li>
<li>Adjusted R² (0.833): prácticamente igual, lo que indica que no hay sobreajuste.</li>
<li>F-statistic (2773, p &lt; 2.2e-16): el modelo en su conjunto es altamente significativo.</li>
</ul>
</section>
<section id="modelo-qr" class="level3">
<h3 class="anchored" data-anchor-id="modelo-qr"><strong>2.2. Modelo QR</strong></h3>
<p>Aquí analizamos cómo los efectos de los predictores cambian en diferentes puntos de la distribución de CO: los cuantiles 0.05 (muy baja contaminación), 0.50 (mediana) y 0.95 (muy alta contaminación).</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call: rq(formula = form, tau = taus, data = df)

tau: [1] 0.05

Coefficients:
                                    Value    Std. Error t value  Pr(&gt;|t|)
(Intercept)                          0.63730  0.11399    5.59091  0.00000
Temperatura                          0.00081  0.00138    0.58359  0.55952
Humedad                              0.00009  0.00034    0.27377  0.78427
PM2.5                               -0.00008  0.00025   -0.33092  0.74072
Cercania_Areas_Industriales         -0.01351  0.00670   -2.01765  0.04368
I(log(Cercania_Areas_Industriales))  0.13814  0.07377    1.87259  0.06118
Densidad_Poblacion                  -0.00002  0.00005   -0.43526  0.66339
Calidad_AireModerate                 0.35961  0.02151   16.71924  0.00000
Calidad_AirePoor                     0.71069  0.03512   20.23738  0.00000
Calidad_AireHazardous                1.11754  0.05404   20.68166  0.00000

Call: rq(formula = form, tau = taus, data = df)

tau: [1] 0.25

Coefficients:
                                    Value    Std. Error t value  Pr(&gt;|t|)
(Intercept)                          0.83442  0.09982    8.35961  0.00000
Temperatura                          0.00036  0.00090    0.39626  0.69193
Humedad                             -0.00031  0.00025   -1.26351  0.20646
PM2.5                                0.00005  0.00022    0.23141  0.81700
Cercania_Areas_Industriales         -0.00703  0.00671   -1.04843  0.29449
I(log(Cercania_Areas_Industriales))  0.06917  0.06691    1.03385  0.30126
Densidad_Poblacion                   0.00005  0.00002    1.91577  0.05545
Calidad_AireModerate                 0.44299  0.01208   36.67906  0.00000
Calidad_AirePoor                     0.86837  0.02480   35.01108  0.00000
Calidad_AireHazardous                1.28625  0.04119   31.22803  0.00000

Call: rq(formula = form, tau = taus, data = df)

tau: [1] 0.5

Coefficients:
                                    Value    Std. Error t value  Pr(&gt;|t|)
(Intercept)                          0.97887  0.07884   12.41528  0.00000
Temperatura                          0.00013  0.00088    0.15088  0.88007
Humedad                             -0.00036  0.00023   -1.52065  0.12841
PM2.5                                0.00015  0.00019    0.79511  0.42659
Cercania_Areas_Industriales         -0.00382  0.00485   -0.78802  0.43072
I(log(Cercania_Areas_Industriales))  0.02924  0.05241    0.55792  0.57692
Densidad_Poblacion                   0.00003  0.00002    1.41053  0.15845
Calidad_AireModerate                 0.49335  0.01471   33.53676  0.00000
Calidad_AirePoor                     0.98726  0.02342   42.15572  0.00000
Calidad_AireHazardous                1.45891  0.03807   38.32461  0.00000

Call: rq(formula = form, tau = taus, data = df)

tau: [1] 0.75

Coefficients:
                                    Value    Std. Error t value  Pr(&gt;|t|)
(Intercept)                          0.96649  0.09117   10.60051  0.00000
Temperatura                         -0.00113  0.00084   -1.35119  0.17670
Humedad                             -0.00018  0.00029   -0.62966  0.52894
PM2.5                                0.00032  0.00024    1.34595  0.17838
Cercania_Areas_Industriales         -0.00865  0.00479   -1.80415  0.07127
I(log(Cercania_Areas_Industriales))  0.09348  0.05794    1.61347  0.10671
Densidad_Poblacion                   0.00003  0.00003    0.96548  0.33435
Calidad_AireModerate                 0.58201  0.01479   39.36409  0.00000
Calidad_AirePoor                     1.15693  0.02766   41.82522  0.00000
Calidad_AireHazardous                1.70920  0.04204   40.66085  0.00000

Call: rq(formula = form, tau = taus, data = df)

tau: [1] 0.95

Coefficients:
                                    Value    Std. Error t value  Pr(&gt;|t|)
(Intercept)                          1.13414  0.15474    7.32939  0.00000
Temperatura                         -0.00181  0.00142   -1.27391  0.20275
Humedad                             -0.00011  0.00045   -0.24584  0.80582
PM2.5                                0.00036  0.00042    0.86548  0.38682
Cercania_Areas_Industriales         -0.00059  0.00811   -0.07306  0.94176
I(log(Cercania_Areas_Industriales))  0.01992  0.09739    0.20455  0.83793
Densidad_Poblacion                   0.00009  0.00004    2.00975  0.04451
Calidad_AireModerate                 0.66627  0.02704   24.63978  0.00000
Calidad_AirePoor                     1.33356  0.04376   30.47538  0.00000
Calidad_AireHazardous                2.04209  0.08471   24.10583  0.00000</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Coeficientes de regresión cuantil por variable y cuantiles</caption>
<colgroup>
<col style="width: 40%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">Q0.05</th>
<th style="text-align: right;">Q0.25</th>
<th style="text-align: right;">Q0.5</th>
<th style="text-align: right;">Q0.75</th>
<th style="text-align: right;">Q0.95</th>
<th style="text-align: right;">OLS</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Temperatura</td>
<td style="text-align: right;">0.00081</td>
<td style="text-align: right;">0.00036</td>
<td style="text-align: right;">0.00013</td>
<td style="text-align: right;">-0.00113</td>
<td style="text-align: right;">-0.00181</td>
<td style="text-align: right;">-0.00046</td>
</tr>
<tr class="even">
<td style="text-align: left;">Humedad</td>
<td style="text-align: right;">0.00009</td>
<td style="text-align: right;">-0.00031</td>
<td style="text-align: right;">-0.00036</td>
<td style="text-align: right;">-0.00018</td>
<td style="text-align: right;">-0.00011</td>
<td style="text-align: right;">-0.00023</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PM2.5</td>
<td style="text-align: right;">-0.00008</td>
<td style="text-align: right;">0.00005</td>
<td style="text-align: right;">0.00015</td>
<td style="text-align: right;">0.00032</td>
<td style="text-align: right;">0.00036</td>
<td style="text-align: right;">0.00036</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cercanía_Areas_Industriales</td>
<td style="text-align: right;">-0.01351</td>
<td style="text-align: right;">-0.00703</td>
<td style="text-align: right;">-0.00382</td>
<td style="text-align: right;">-0.00865</td>
<td style="text-align: right;">-0.00059</td>
<td style="text-align: right;">-0.01620</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I(log(Cercanía_Areas_Industriales))</td>
<td style="text-align: right;">0.13814</td>
<td style="text-align: right;">0.06917</td>
<td style="text-align: right;">0.02924</td>
<td style="text-align: right;">0.09348</td>
<td style="text-align: right;">0.01992</td>
<td style="text-align: right;">0.10250</td>
</tr>
<tr class="even">
<td style="text-align: left;">Densidad_Población</td>
<td style="text-align: right;">-0.00002</td>
<td style="text-align: right;">0.00005</td>
<td style="text-align: right;">0.00003</td>
<td style="text-align: right;">0.00003</td>
<td style="text-align: right;">0.00009</td>
<td style="text-align: right;">0.00003</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Calidad_AireModerate</td>
<td style="text-align: right;">0.35961</td>
<td style="text-align: right;">0.44299</td>
<td style="text-align: right;">0.49335</td>
<td style="text-align: right;">0.58201</td>
<td style="text-align: right;">0.66627</td>
<td style="text-align: right;">0.50300</td>
</tr>
<tr class="even">
<td style="text-align: left;">Calidad_AirePoor</td>
<td style="text-align: right;">0.71069</td>
<td style="text-align: right;">0.86837</td>
<td style="text-align: right;">0.98726</td>
<td style="text-align: right;">1.15693</td>
<td style="text-align: right;">1.33356</td>
<td style="text-align: right;">1.00600</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Calidad_AireHazardous</td>
<td style="text-align: right;">1.11754</td>
<td style="text-align: right;">1.28625</td>
<td style="text-align: right;">1.45891</td>
<td style="text-align: right;">1.70920</td>
<td style="text-align: right;">2.04209</td>
<td style="text-align: right;">1.50600</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="resultados-gráficos" class="level3">
<h3 class="anchored" data-anchor-id="resultados-gráficos"><strong>2.3. Resultados gráficos</strong></h3>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Modelo_QR_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><strong>Temperatura</strong>: Su efecto va decreciendo a través de los cuantiles. Sin embargo, <strong>no es significativo</strong> en todos los tau. En cuánto al modelo OLS, <strong>sobreestima</strong> en la base y <strong>subestima</strong> en la cúpula.</li>
<li><strong>Humedad</strong>: Su impacto es positivo en el quantil 0.05, pero negativo creciente a partir del cuantil 0.25. Sin embargo, al igual que la temperatura, <strong>no es significativo</strong> en todos los tau.</li>
<li><strong>PM2.5</strong>: Tiene un impacto negativo en la base y va creciendo. Sin embargo, <strong>no es significativo</strong> en todos los tau.</li>
<li><strong>Cercania Areas Industriales</strong>: la parte lineal presenta una tendencia creciente en los taus, teniendo un impacto negativo (a mayor distancia, menores los nievels de CO). Sin embargo, esta variable <strong>solo es significativa</strong> en los cuantiles 0.05 y 0.75. La parte logarítmica presenta una tendencia decreciente en los taus, sin emabrgo <strong>no es significativa</strong> en ningún tau.</li>
<li><strong>Densidad de Población</strong>: su efecto es negativo en la base y tiende a crecer muy poco a través de los taus.Sin embargo, <strong>no es significativa</strong>.</li>
<li><strong>Calidad del aire</strong>: en todos los casos, la calidad del aire es significativa y es creciente en todos los taus. Además, con base en los gráficos, su crecimiento es constante (lineal), pero hay una brecha un poco mayor en la cúpula, lo que indica que los niveles de CO son cada vez mayores a medica que la calidad del aire va empeorando.</li>
</ul>
</section>
<section id="modelo-qr-con-interacción" class="level3">
<h3 class="anchored" data-anchor-id="modelo-qr-con-interacción"><strong>2.4. Modelo QR con interacción</strong></h3>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Modelo_QR_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Comparación de la cercanía con la calidad del aire:</p>
<ul>
<li><p><strong>Zonas de mejor calidad de aire (“Good” y “Moderate”)</strong>: En estas condiciones, la cercanía a un área industrial tiene un efecto mínimo-medio sobre los niveles de CO. No importa si se analizan los niveles promedio (OLS), los más bajos (τ=0.05) o los más altos (τ=0.95); la proximidad no es un factor determinante. Aquí, el OLS y la QR cuentan una historia similar. Sin embargo, las pendientes en calidad de aire moderada muestran una inclinación positiva, aunque no muy pronunciada, indicando que la cercanía industrial empieza a tener un efecto perceptible, especialmente en los valores más altos de CO.</p></li>
<li><p><strong>Zonas de baja calidad de aire (“Poor” y “Hazardous”)</strong>: en estas zonas, la interacción entre calidad de aire y la cercania es mayor, lo que indica que la cercanía a zonas industriales se asocia claramente con un aumento en los niveles de CO. En zonas en el que la calidad de aire es pobre (poor), la proximidad a fuentes industriales contribuye significativamente a la contaminación por CO, afectando incluso los valores bajos (cuantil 0.05), mientras que, cuando la calidad del aire ya es peligrosa (Hazardous), la exposición a fuentes industriales es crítica. Incluso a distancias moderadas, los niveles de CO son peligrosamente altos.</p></li>
</ul>
<p>Los dos puntos anteriores nos dicen que, la interacción entre la calidad del aire y la cercanía no es lineal ni uniforme, y la influencia de la cercanía es más fuerte en regiones en el que la calidad del aire es pobre o peligroso.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>